apiVersion: v1
kind: Pod
metadata:
  name: aws-ubuntu-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}

  containers:
    - name: aws-cli
      image: amazon/aws-cli
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/data

    - name: ubuntu
      image: ubuntu
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/data
